/**
 * Codes d'actions journalisées (RG-LOG-01 : « connexions (succès/échec), création/modification/
 * suppression de comptes, changements de rôles, saisie/modification d'évaluations, génération de
 * documents, exports, demandes RGPD », complété des événements de sécurité du chapitre 10).
 */
export const ActionJournal = {
  // Authentification (UC-01, UC-02)
  CONNEXION_REUSSIE: 'CONNEXION_REUSSIE',
  CONNEXION_ECHOUEE: 'CONNEXION_ECHOUEE',
  VERROUILLAGE_COMPTE: 'VERROUILLAGE_COMPTE',
  DECONNEXION: 'DECONNEXION',
  MFA_ECHEC: 'MFA_ECHEC',
  MFA_ACTIVATION: 'MFA_ACTIVATION',
  MFA_DESACTIVATION: 'MFA_DESACTIVATION',
  REINITIALISATION_DEMANDEE: 'REINITIALISATION_DEMANDEE',
  MOT_DE_PASSE_MODIFIE: 'MOT_DE_PASSE_MODIFIE',
  ACTIVATION_COMPTE: 'ACTIVATION_COMPTE',
  REUTILISATION_JETON: 'REUTILISATION_JETON',
  ACCES_REFUSE: 'ACCES_REFUSE',

  // Comptes et paramètres (UC-03)
  CREATION_COMPTE: 'CREATION_COMPTE',
  MODIFICATION_COMPTE: 'MODIFICATION_COMPTE',
  CHANGEMENT_ROLE: 'CHANGEMENT_ROLE',
  DEVERROUILLAGE_COMPTE: 'DEVERROUILLAGE_COMPTE',
  SUPPRESSION_COMPTE: 'SUPPRESSION_COMPTE',
  ANONYMISATION_COMPTE: 'ANONYMISATION_COMPTE',
  CREATION_ENTREPRISE: 'CREATION_ENTREPRISE',
  MODIFICATION_ENTREPRISE: 'MODIFICATION_ENTREPRISE',
  MODIFICATION_PARAMETRE: 'MODIFICATION_PARAMETRE',

  // Catalogue (UC-04)
  CREATION_FORMATION: 'CREATION_FORMATION',
  MODIFICATION_FORMATION: 'MODIFICATION_FORMATION',
  CHANGEMENT_STATUT_FORMATION: 'CHANGEMENT_STATUT_FORMATION',
  SUPPRESSION_FORMATION: 'SUPPRESSION_FORMATION',
  CREATION_COMPETENCE: 'CREATION_COMPETENCE',
  MODIFICATION_COMPETENCE: 'MODIFICATION_COMPETENCE',
  SUPPRESSION_COMPETENCE: 'SUPPRESSION_COMPETENCE',

  // Sessions et inscriptions (UC-05, UC-06)
  CREATION_SESSION: 'CREATION_SESSION',
  MODIFICATION_SESSION: 'MODIFICATION_SESSION',
  SUPPRESSION_SESSION: 'SUPPRESSION_SESSION',
  AFFECTATION_FORMATEUR: 'AFFECTATION_FORMATEUR',
  RETRAIT_FORMATEUR: 'RETRAIT_FORMATEUR',
  INSCRIPTION_APPRENANT: 'INSCRIPTION_APPRENANT',
  CHANGEMENT_STATUT_INSCRIPTION: 'CHANGEMENT_STATUT_INSCRIPTION',

  // Évaluations (UC-08)
  SAISIE_NOTE: 'SAISIE_NOTE',
  CORRECTION_NOTE: 'CORRECTION_NOTE',

  // Documents et exports (UC-09, UC-11)
  GENERATION_DOCUMENT: 'GENERATION_DOCUMENT',
  TELECHARGEMENT_DOCUMENT: 'TELECHARGEMENT_DOCUMENT',
  INTEGRITE_DOCUMENT: 'INTEGRITE_DOCUMENT',
  EXPORT_CSV: 'EXPORT_CSV',
  EXPORT_PDF: 'EXPORT_PDF',
  REPONSE_SATISFACTION: 'REPONSE_SATISFACTION',

  // RGPD (UC-13, UC-14)
  CONSULTATION_DONNEES_PERSONNELLES: 'CONSULTATION_DONNEES_PERSONNELLES',
  EXPORT_DONNEES_PERSONNELLES: 'EXPORT_DONNEES_PERSONNELLES',
  RECTIFICATION_DONNEES: 'RECTIFICATION_DONNEES',
  CONSENTEMENT_DONNE: 'CONSENTEMENT_DONNE',
  CONSENTEMENT_RETIRE: 'CONSENTEMENT_RETIRE',
  DEMANDE_RGPD: 'DEMANDE_RGPD',
  TRAITEMENT_DEMANDE_RGPD: 'TRAITEMENT_DEMANDE_RGPD',
  PURGE_CONSERVATION: 'PURGE_CONSERVATION',
} as const;

export type ActionJournal = (typeof ActionJournal)[keyof typeof ActionJournal];
